import { Inter } from "next/font/google";
import Header from "./components/Header"; // Adjust the import path as needed
import './globals.css';
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-50`}>
        <Header /> {/* Include the Header component here */}
        <main>{children}</main>
      </body>
    </html>
  );
}
